import { useState } from "react";
import Head from "next/head";
import { Poppins } from "next/font/google";
import styled from "styled-components";
import Sidebar from "@/components/Sidebar/Sidebar";
import Chat from "@/components/Chat/Chat";
import Billboard from "@/components/Billboard/Billboard";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export default function Home() {
  const [isChatOpen, setIsChatOpen] = useState(false);

  return (
    <>
      <Head>
        <title>WhatsGood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={poppins.className}>
        <HomeLayout>
          <Sidebar openChat={setIsChatOpen} />
          {isChatOpen ? <Chat /> : <Billboard />}
        </HomeLayout>
      </main>
    </>
  );
}

const HomeLayout = styled.div`
  display: flex;
  height: 100vh;
`;
