import Head from "next/head";
import { Poppins } from "next/font/google";
import styled from "styled-components";
import Sidebar from "@/components/Sidebar/Sidebar";
import Chat from "@/components/Chat/Chat";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>WhatsGood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={poppins.className}>
        <HomeLayout>
          <Sidebar />
          <Chat />
        </HomeLayout>
      </main>
    </>
  );
}

const HomeLayout = styled.div`
  display: flex;
  height: 100vh;
`;
